### ISSUE TITLE
Two samples are failing

### ISSUE THREAD

**Issue by Sarbojit2019** [CHIP-SPV/chip-spv#153]
Observed two failures while running "**make check**" on my setup. My configuration is ATS + intel_compute_runtime_475 + clang 14

        578 - hip_async_binomial (SEGFAULT)
        597 - hipNormalizedFloat (Failed)

While running it standalone, below is the failure output observed for hipNormalizedFloat. Looked further and found data type 'char' and 'short' subtests are failing with exact same indexes not matching every time. If I comment out char and short cases rest of the test passes without any issue.

**Failed output**
<my_server>:~/src/chip-spv/build/samples/texture> ./hipNormalizedFloat
Error at [0][5]: Expected '-0.566929'. Got '-0.566929'
Error at [3][2]: Expected '-0.818898'. Got '-0.818898'
Error at [6][6]: Expected '-0.283465'. Got '-0.283465'
Error at [7][2]: Expected '0.818898'. Got '0.818898'

**Comment by pvelesko** [comment]
I thought I fixed this already. Can you make sure that your `main` branch is up to date ?

**Comment by Sarbojit2019** [comment]
@pvelesko,
Yes, I see latest 'main' has got the fix for floating point comparison. Test : hipNormalizedFloat passes now but I still see **hip_async_binomial** is failing and there are few new tests failures observed.

        176 - Unit_hipMemset2DAsync_MultiThread (Timeout)
        581 - Stress_hipMemcpy_multiDevice-AllAPIs - int (Failed)
        582 - Stress_hipMemcpy_multiDevice-AllAPIs - size_t (Failed)
        583 - Stress_hipMemcpy_multiDevice-AllAPIs - long double (Failed)
        618 - hip_async_binomial (SEGFAULT)

My configuration : Intel_compute_runtime_475 + Clang 14 + ATS GPU

**Comment by pvelesko** [comment]
> Yes, I see latest 'main' has got the fix for floating point comparison 

That's strange because if you were on the Release-0.9 branch then the fix should have already been in there. Please check that your submodules are up to date.

**Comment by Sarbojit2019** [comment]
581 - Stress_hipMemcpy_multiDevice-AllAPIs - int (Failed)
    582 - Stress_hipMemcpy_multiDevice-AllAPIs - size_t (Failed)
    583 - Stress_hipMemcpy_multiDevice-AllAPIs - long double (Failed)

Looks like tests are failing due to OOM (out of memory), hipMalloc is failing with hipErrorOutOfMemory.

_CHIP error [TID 20142] [1663830524.083037783] : hipErrorOutOfMemory (ZE_RESULT_ERROR_UNSUPPORTED_SIZE ) in /home/sarbojit/src/chip-spv/src/backend/Level0/CHIPBackendLevel0.cc:1539:allocateImpl
CHIP error [TID 20142] [1663830524.083130936] : Caught Error: hipErrorOutOfMemory_

I am on latest 'main' + Clang 15 + Intel_compute_runtime_475 + ATS GPU + GPU memory ~30GB.

To me looks like even though hipFree is called it is not really clearing the memory hence test is getting OOM.

**Comment by pjaaskel** [comment]
Does it fail also with the OpenCL BE?

**Comment by pvelesko** [comment]
The allocation requested exceeds the maximum allocation size for Level Zero. Need to look into why it wasn't caught prior to the allocation request.

**Comment by pvelesko** [comment]
For the `Stress_hipMemcpy_multiDevice-AllAPIs` test, 

Can you paste the last test case for the file `HIP/tests/catch/stress/memory/hipMemcpyMThreadMSize.cc` here?
